package com.lnu.agile.model;
// Generated Dec 2, 2015 2:28:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TpsUser generated by hbm2java
 */
@Entity
@Table(name = "tps_user")
public class TpsUser implements java.io.Serializable {

    @Id
    @Column(name = "user_id")
    private int userId;

    @Column(name = "user_email")
    private String userEmail;

    @Column(name = "user_confirmed")
    private boolean userConfirmed;

    @Column(name = "user_confirmtoken")
    private String userConfirmtoken;

    @Column(name = "user_password")
    private String userPassword;

    @Column(name = "user_accountname")
    private String userAccountname;

    @Column(name = "user_firstname")
    private String userFisrtname;

    @Column(name = "user_lastname")
    private String userLastname;

    @Column(name = "user_userphone")
    private String userPhone;

    public TpsUser() {
    }

    public TpsUser(String userEmail, boolean userConfirmed) {
        this.userEmail = userEmail;
        this.userConfirmed = userConfirmed;
    }

    public TpsUser(String userEmail, boolean userConfirmed, String userConfirmtoken, String userPassword, String userAccountname, String userFisrtname, String userLastname, String userPhone) {
        this.userEmail = userEmail;
        this.userConfirmed = userConfirmed;
        this.userConfirmtoken = userConfirmtoken;
        this.userPassword = userPassword;
        this.userAccountname = userAccountname;
        this.userFisrtname = userFisrtname;
        this.userLastname = userLastname;
        this.userPhone = userPhone;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserEmail() {
        return this.userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public boolean isUserConfirmed() {
        return this.userConfirmed;
    }

    public void setUserConfirmed(boolean userConfirmed) {
        this.userConfirmed = userConfirmed;
    }

    public String getUserConfirmtoken() {
        return this.userConfirmtoken;
    }

    public void setUserConfirmtoken(String userConfirmtoken) {
        this.userConfirmtoken = userConfirmtoken;
    }

    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public String getUserAccountname() {
        return this.userAccountname;
    }

    public void setUserAccountname(String userAccountname) {
        this.userAccountname = userAccountname;
    }

    public String getUserFisrtname() {
        return this.userFisrtname;
    }

    public void setUserFisrtname(String userFisrtname) {
        this.userFisrtname = userFisrtname;
    }

    public String getUserLastname() {
        return this.userLastname;
    }

    public void setUserLastname(String userLastname) {
        this.userLastname = userLastname;
    }

    public String getUserPhone() {
        return this.userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
}
