package com.lnu.agile.db.model.pojo;
// Generated Dec 2, 2015 2:28:02 PM by Hibernate Tools 4.3.1



/**
 * TpsUser generated by hbm2java
 */
public class TpsUser  implements java.io.Serializable {


     private Integer userId;
     private String userEmail;
     private boolean userConfirmed;
     private String userConfirmtoken;
     private String userPassword;
     private String userAccountname;
     private String userFisrtname;
     private String userLastname;
     private String userPhone;

    public TpsUser() {
    }

	
    public TpsUser(String userEmail, boolean userConfirmed) {
        this.userEmail = userEmail;
        this.userConfirmed = userConfirmed;
    }
    public TpsUser(String userEmail, boolean userConfirmed, String userConfirmtoken, String userPassword, String userAccountname, String userFisrtname, String userLastname, String userPhone) {
       this.userEmail = userEmail;
       this.userConfirmed = userConfirmed;
       this.userConfirmtoken = userConfirmtoken;
       this.userPassword = userPassword;
       this.userAccountname = userAccountname;
       this.userFisrtname = userFisrtname;
       this.userLastname = userLastname;
       this.userPhone = userPhone;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public boolean isUserConfirmed() {
        return this.userConfirmed;
    }
    
    public void setUserConfirmed(boolean userConfirmed) {
        this.userConfirmed = userConfirmed;
    }
    public String getUserConfirmtoken() {
        return this.userConfirmtoken;
    }
    
    public void setUserConfirmtoken(String userConfirmtoken) {
        this.userConfirmtoken = userConfirmtoken;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserAccountname() {
        return this.userAccountname;
    }
    
    public void setUserAccountname(String userAccountname) {
        this.userAccountname = userAccountname;
    }
    public String getUserFisrtname() {
        return this.userFisrtname;
    }
    
    public void setUserFisrtname(String userFisrtname) {
        this.userFisrtname = userFisrtname;
    }
    public String getUserLastname() {
        return this.userLastname;
    }
    
    public void setUserLastname(String userLastname) {
        this.userLastname = userLastname;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }




}


