package com.lnu.agile.db.model.pojo;
// Generated Nov 30, 2015 5:44:23 PM by Hibernate Tools 4.3.1



/**
 * TpsUser generated by hbm2java
 */
public class TpsUser  implements java.io.Serializable {


     private Integer userid;
     private String userEmail;
     private Integer userStatus;
     private String userPassword;
     private String userName;
     private String userPhone;

    public TpsUser() {
    }

	
    public TpsUser(String userEmail) {
        this.userEmail = userEmail;
    }
    public TpsUser(String userEmail, Integer userStatus, String userPassword, String userName, String userPhone) {
       this.userEmail = userEmail;
       this.userStatus = userStatus;
       this.userPassword = userPassword;
       this.userName = userName;
       this.userPhone = userPhone;
    }
   
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Integer getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }




}


